services:
  postgres:
    image: postgres:15
    container_name: checkout_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkout
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: checkout_rabbitmq
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: checkout_app
    restart: always
    command: yarn start:dev
    volumes:
      - .:/app        
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/checkout?schema=public"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"

volumes:
  postgres_data: